apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJWMkZ5WkdGeUxYQjVPbWRvY0Y4d1dXTlhORE0zWW0weGFEaFRVREV4VUV0Q1FUaHdjbXgwUjJ0SE5GazBRMncwWjNZPSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
